# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=15)),
                ('salary_year', models.IntegerField()),
                ('no_of_days', models.IntegerField()),
                ('no_of_days_worked', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_details.Employee')),
            ],
        ),
    ]
