# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_fname',
            field=models.CharField(max_length=250, verbose_name='First Name'),
        ),
    ]
