# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0003_auto_20190909_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_email',
            field=models.CharField(max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_lname',
            field=models.CharField(max_length=250, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_mname',
            field=models.CharField(max_length=250, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
    ]
