# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0004_auto_20190909_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='no_of_days',
            field=models.IntegerField(verbose_name='No. of working days'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='no_of_days_worked',
            field=models.IntegerField(verbose_name='No. of days worked'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='salary_month',
            field=models.CharField(max_length=15, verbose_name='Salary Month'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='salary_year',
            field=models.IntegerField(verbose_name='Salary Year'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='CTC_Year',
            field=models.IntegerField(verbose_name='CTC p.a'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='other_allowances',
            field=models.FloatField(verbose_name='Other Allowances'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='other_deductions',
            field=models.FloatField(verbose_name='Other Deductions'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_month',
            field=models.CharField(max_length=15, verbose_name='Salary Month'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_year',
            field=models.IntegerField(verbose_name='Salary Year'),
        ),
    ]
