# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0006_employee_e_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='leave_month_year',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='payroll_details.Leave'),
            preserve_default=False,
        ),
    ]
