# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0008_auto_20190910_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.CharField(max_length=15, verbose_name='Salary Month')),
                ('salary_year', models.IntegerField(verbose_name='Salary Year')),
                ('no_of_days', models.IntegerField(verbose_name='No. of working days')),
                ('no_of_days_worked', models.IntegerField(verbose_name='No. of days worked')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll_details.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='salary',
            name='no_of_days',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='no_of_days_worked',
        ),
    ]
