# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-09-09 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_details', '0009_auto_20190910_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='emp',
        ),
        migrations.AddField(
            model_name='salary',
            name='no_of_days',
            field=models.IntegerField(default=0, verbose_name='No. of working days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='no_of_days_worked',
            field=models.IntegerField(default=0, verbose_name='No. of days worked'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
